apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"version":"v1","zone":"prod"},"name":"hello-pod","namespace":"default"},"spec":{"containers":[{"image":"nigelpoulton/k8sbook:1.0","name":"hello-ctr","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":0.5,"memory":"256Mi"}}}]}}
  creationTimestamp: "2024-10-21T09:35:47Z"
  labels:
    version: v1
    zone: prod
  name: hello-pod
  namespace: default
  resourceVersion: "4688"
  uid: c6a4e4ce-7449-42f9-92fe-348a423c7d20
spec:
  containers:
  - image: nigelpoulton/k8sbook:1.0
    imagePullPolicy: IfNotPresent
    name: hello-ctr
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gptgr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-gptgr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-21T09:38:16Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-10-21T09:35:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-21T09:38:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-21T09:38:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-21T09:35:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://56a261400178286cf22322ddb16ca8aff2e6591c9ae0d72c207ae86dbb3b2285
    image: nigelpoulton/k8sbook:1.0
    imageID: docker-pullable://nigelpoulton/k8sbook@sha256:3c02d99771460006364b32528e898f7ea33ad0797d77e7892264b0539dbaca9a
    lastState: {}
    name: hello-ctr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-10-21T09:38:15Z"
  hostIP: 192.168.65.3
  hostIPs:
  - ip: 192.168.65.3
  phase: Running
  podIP: 10.1.0.6
  podIPs:
  - ip: 10.1.0.6
  qosClass: Guaranteed
  startTime: "2024-10-21T09:35:47Z"
